# Utilisez l'image de base Alpine
FROM alpine

# Déclarez le volume
VOLUME /data

# Commande pour garder le conteneur en cours d'exécution pour permettre les interactions
CMD ["sh", "-c", "while true; do sleep 30; done"]
